// Locales
export const LOCALES_GET_INFO_SUCCESS = 'LOCALES_GET_INFO_SUCCESS';

// Settings
export const SETTINGS_GET_SUCCESS = 'SETTINGS_GET_SUCCESS';

// Home Page
export const HOME_GET_INFO_SUCCESS = 'HOME_GET_INFO_SUCCESS';

// Dashboard Page
export const DASHBOARD_GET_INFO_SUCCESS = 'DASHBOARD_GET_INFO_SUCCESS';

// Unit Page
export const UNIT_GET_INFO_SUCCESS = 'UNIT_GET_INFO_SUCCESS';
export const UNIT_SUBMIT = 'UNIT_SUBMIT';

// User Profile
export const USER_PROFILE_GET_SUCCESS = 'USER_PROFILE_GET_SUCCESS';
export const USER_PROFILE_CHANGE_LANG = 'USER_PROFILE_CHANGE_LANG';

// Roles
export const ROLES_GET_INFO_SUCCESS = 'ROLES_GET_INFO_SUCCESS';

// Modules
export const MODULES_GET_INFO_SUCCESS = 'MODULES_GET_INFO_SUCCESS';
export const MODULES_GET_ITEM_SUCCESS = 'MODULES_GET_ITEM_SUCCESS';
